site_name: 'Giveth Wiki'
site_url: https://wiki.giveth.io
site_author: 'The Giveth DAC'
site_description: 'Learn about Giveth'
repo_name: '/giveth-wiki'
repo_url: https://github.com/Giveth/giveth-wiki/
edit_uri: edit/master/wiki/
docs_dir: wiki

theme:
  name: 'material'
  custom_dir: 'material'
  palette:
    primary: 'deep purple'
    accent: 'deep purple'
  language: 'en'

google_analytics: ['UA-103956937-1', 'giveth.io']

extra:
    palette:
      primary: 'deep purple'
      accent: 'green'
    social:
    - type: 'comment-o'
      link: 'http://join.giveth.io/'
    - type: 'medium'
      link: 'https://medium.com/giveth'
    - type: 'twitter'
      link: 'https://twitter.com/givethio'
    - type: 'github'
      link: 'https://github.com/giveth'
    - type: 'facebook'
      link: 'https://facebook.com/givethio'
    - type: 'youtube'
      link: 'https://www.youtube.com/watch?v=VaIbmxk2eio&list=PL4Artm1rmCWGyz-BWv1-8Ip26XIauCLo9'

extra_css:
    - css/extra.css

pages:
    - Welcome: 'index.md'

    - General Info:
        - Calendar and Events: 'dac/calendar.md'
        - About the Team: 'dac/about.md'
        - FAQ: 'documentation/faq.md'
        - Glossary: 'documentation/glossary.md'

    - Tutorials and Guides:
        - Contributors Guide: 'dac/contributors-guide.md'
        - Riot.im: 'tutorials/riot-migration.md'
        - Video Content Strategy: 'documentation/video-content-strategy.md'
        - Visual Identity Guide: 'documentation/visual-identity.md'
        - Brand Identity Guide: 'documentation/Branding_Guidelines.md'

    - Giveth Donation Application (DApp):
        - DApp Alpha: 'documentation/DApp/alpha.md'
        - DApp White Paper: 'documentation/DApp/white-paper.md'
        - Product Definition: 'documentation/DApp/product-definition.md'
        - Development Process & Quality Assurance: 'documentation/DApp/product-development-testing.md'
        - Roadmap: 'documentation/DApp/product-roadmap.md'
        - Future: 'documentation/DApp/future.md'
        - Exchange Rate Calculation: 'documentation/DApp/exchange-rate-calculation.md'

    - Giveth Smart Contracts:
        - Deployments: 'documentation/deployments.md'
        - Smart Contracts Roadmap: 'documentation/smart-contracts-roadmap.md'

    - Giveth Community (DAC):
        - Governance model: 'dac/governance.md'
        - History: 'dac/history.md'
        - Team Organisation: 'dac/team-organisation.md'
        - Tools for DACs: 'dac/tools-for-dacs.md'
        - Finances: 'dac/finances.md'

    - Policy:
        - Protocol for Governance Meetings: 'protocol/governance-meetings.md'
        - Code of Conduct: 'policy/codeofconduct.md'

    - Protocol:
          - Governance Meetings:
            - Governance Meeting 01: 'protocol/gov-meeting-1.md'
            - Governance Meeting 02: 'protocol/gov-meeting-2.md'
            - Governance Meeting 03: 'protocol/gov-meeting-3.md'
            - Governance Meeting 04: 'protocol/gov-meeting-4.md'
            - Governance Meeting 05: 'protocol/gov-meeting-5.md'
            - Governance Meeting 06: 'protocol/gov-meeting-6.md'
            - Governance Meeting 07: 'protocol/gov-meeting-7.md'
            - Governance Meeting 08: 'protocol/gov-meeting-8.md'
            - Governance Meeting 09: 'protocol/gov-meeting-9.md'
            - Governance Meeting 10: 'protocol/gov-meeting-10.md'
            - Governance Meeting 11: 'protocol/gov-meeting-11.md'
            - Governance Meeting 12: 'protocol/gov-meeting-12.md'
            - Governance Meeting 13: 'protocol/gov-meeting-13.md'
            - Governance Meeting 14: 'protocol/gov-meeting-14.md'
            - Governance Meeting 15: 'protocol/gov-meeting-15.md'
            - Governance Meeting 16: 'protocol/gov-meeting-16.md'
            - Governance Meeting 17: 'protocol/gov-meeting-17.md'
            - Governance Meeting 18: 'protocol/gov-meeting-18.md'
            - Governance Meeting 19: 'protocol/gov-meeting-19.md'
            - Governance Meeting 20: 'protocol/gov-meeting-20.md'
            - Governance Meeting 21: 'protocol/gov-meeting-21.md'
            - Governance Meeting 25: 'protocol/gov-meeting-25.md'
            - Governance Meeting 28: 'protocol/gov-meeting-26.md'
            - Governance Meeting 27: 'protocol/gov-meeting-27.md'
            - Governance Meeting 28: 'protocol/gov-meeting-28.md'
            - Governance Meeting 30: 'protocol/gov-meeting-30.md'
            - Governance Meeting 31: 'protocol/gov-meeting-31.md'
            - Governance Meeting 32: 'protocol/gov-meeting-32.md'
            - Governance Meeting 33: 'protocol/gov-meeting-33.md'
            - Onboarding Meeting: 'protocol/onboarding-meeting.md'            
    - Publicity and News: 'publicity/in-the-news.md'
