site_name: 'Giveth Wiki'
site_url: https://wiki.giveth.io
site_author: 'The Giveth DAC'
site_description: 'Learn about Giveth'
repo_name: '/giveth-wiki'
repo_url: https://github.com/Giveth/giveth-wiki/
edit_uri: edit/master/wiki/
docs_dir: wiki

theme:
  name: 'material'
  custom_dir: 'material'
  palette:
    primary: 'deep purple'
    accent: 'deep purple'
  language: 'en'

google_analytics: ['UA-103956937-1', 'giveth.io']

extra:
    palette:
      primary: 'deep purple'
      accent: 'green'
    social:
    - type: 'comment-o'
      link: 'http://join.giveth.io/'
    - type: 'medium'
      link: 'https://medium.com/giveth'
    - type: 'twitter'
      link: 'https://twitter.com/givethio'
    - type: 'github'
      link: 'https://github.com/giveth'
    - type: 'facebook'
      link: 'https://facebook.com/givethio'
    - type: 'youtube'
      link: 'https://www.youtube.com/watch?v=VaIbmxk2eio&list=PL4Artm1rmCWGyz-BWv1-8Ip26XIauCLo9'

extra_css:
    - css/extra.css

nav:
    - Welcome: 'index.md'
    - General:
        - Our Mission: 'dac/mission.md'
        - Calendar & Events: 'dac/calendar.md'
    - Dapp Development:
      - Intro to the Giveth dapp: 'dapp/index.md'
      - Product Definition: 'dapp/product-definition.md'
      - Roadmap: 'dapp/product-roadmap.md'
      - Documentation & Tutorials:
        - How to make Milestones: 'dapp/milestones.md'
        - Future: 'dapp/future.md'
        - Exchange Rate: 'dapp/exchange-rate-calculation.md'
        - Dev Process & QA: 'dapp/product-development-testing.md'
        - Smart Contracts Roadmap: 'dapp/smart-contracts-roadmap.md'
        - Deployments: 'dapp/deployments.md'
        - Technical Challenges: 'dapp/technical-challenges.md'
    - Social Coding:
      - Intro to Giveth Social Coding: 'social-coding/index.md'
    - Governance:
      - Intro to Giveth Governance: 'governance/index.md'
      - Tools for DACs: 'governance/tools-for-dacs.md'
      - Governance Experiments:
        - Unicorn DAC:
          - Unicorn DAC Intro: 'governance/unicorn-dac/index.md'
          - Unicorn Onboarding: 'governance/unicorn-dac/unicorn-onboarding.md'
          - Get Funding: 'governance/unicorn-dac/unicorn-dac-getfunded.md'
          - Roles Process: 'governance/unicorn-dac/roles.md'
          - Known Unicorns: 'governance/unicorn-dac/unicorns.md'
      - Documentation & Tutorials:
        - Code of Conduct: 'governance/codeofconduct.md'
        - Conflict Resolution: 'governance/conflict-res.md'
        - Governance of Meetings: 'governance/governance-meetings.md'
        - Advice Process: 'governance/advice-process.md'
    - Communications:
       - Intro to Giveth Communications: 'communications/index.md'
       - Documentation & Tutorials:
          - Brand Identity Guide: 'communications/brand-guidelines.md'
          - Use of Riot Chat: 'communications/riot-migration.md'
    - Giveth Community (DAC):
        - Welcome to the Giveth DAC: 'dac/index.md'
        - Team Organisation: 'dac/team-organisation.md'
        - Mission: 'dac/mission.md'
        - Goals: 'dac/goals.md'
        - Finances: 'dac/finances.md'
        - History: 'dac/history.md'
        - Documentation & Tutorials:
          - Contributors Guide: 'dac/contributors-guide.md'
          - Adopted Policies: 'dac/approved-policies.md'
          - Meeting Notes:
            - About our DAC Meetings: 'dac/meeting-notes/index.md'
            - Governance Meeting 01: 'dac/meeting-notes/gov-meeting-1.md'
            - Governance Meeting 02: 'dac/meeting-notes/gov-meeting-2.md'
            - Governance Meeting 03: 'dac/meeting-notes/gov-meeting-3.md'
            - Governance Meeting 04: 'dac/meeting-notes/gov-meeting-4.md'
            - Governance Meeting 05: 'dac/meeting-notes/gov-meeting-5.md'
            - Governance Meeting 06: 'dac/meeting-notes/gov-meeting-6.md'
            - Governance Meeting 07: 'dac/meeting-notes/gov-meeting-7.md'
            - Governance Meeting 08: 'dac/meeting-notes/gov-meeting-8.md'
            - Governance Meeting 09: 'dac/meeting-notes/gov-meeting-9.md'
            - Governance Meeting 10: 'dac/meeting-notes/gov-meeting-10.md'
            - Governance Meeting 11: 'dac/meeting-notes/gov-meeting-11.md'
            - Governance Meeting 12: 'dac/meeting-notes/gov-meeting-12.md'
            - Governance Meeting 13: 'dac/meeting-notes/gov-meeting-13.md'
            - Governance Meeting 14: 'dac/meeting-notes/gov-meeting-14.md'
            - Governance Meeting 15: 'dac/meeting-notes/gov-meeting-15.md'
            - Governance Meeting 16: 'dac/meeting-notes/gov-meeting-16.md'
            - Governance Meeting 17: 'dac/meeting-notes/gov-meeting-17.md'
            - Governance Meeting 18: 'dac/meeting-notes/gov-meeting-18.md'
            - Governance Meeting 19: 'dac/meeting-notes/gov-meeting-19.md'
            - Governance Meeting 20: 'dac/meeting-notes/gov-meeting-20.md'
            - Governance Meeting 21: 'dac/meeting-notes/gov-meeting-21.md'
            - Governance Meeting 25: 'dac/meeting-notes/gov-meeting-25.md'
            - Governance Meeting 26: 'dac/meeting-notes/gov-meeting-26.md'
            - Governance Meeting 27: 'dac/meeting-notes/gov-meeting-27.md'
            - Governance Meeting 28: 'dac/meeting-notes/gov-meeting-28.md'
            - Governance Meeting 30: 'dac/meeting-notes/gov-meeting-30.md'
            - Governance Meeting 31: 'dac/meeting-notes/gov-meeting-31.md'
            - Governance Meeting 32: 'dac/meeting-notes/gov-meeting-32.md'
            - Governance Meeting 33: 'dac/meeting-notes/gov-meeting-33.md'
            - Onboarding Meeting: 'dac/meeting-notes/onboarding-meeting.md'
            - Governance Meeting 34: 'dac/meeting-notes/gov-meeting-34.md'
            - Governance Meeting 35: 'dac/meeting-notes/gov-meeting-35.md'
            - Transparency Meeting: 'dac/meeting-notes/transparency-meeting.md'
            - Governance Meeting 36: 'dac/meeting-notes/gov-meeting-36.md'
            - Governance Meeting 37: 'dac/meeting-notes/gov-meeting-37.md'
            - Governance Meeting 38: 'dac/meeting-notes/gov-meeting-38.md'
            - Governance Meeting 39: 'dac/meeting-notes/gov-meeting-39.md'
            - Governance Meeting 40: 'dac/meeting-notes/gov-meeting-40.md'
            - Governance Meeting 41: 'dac/meeting-notes/gov-meeting-41.md'
            - Governance Meeting 42: 'dac/meeting-notes/gov-meeting-42.md'
            - Roles Meeting 1: 'dac/meeting-notes/roles-meeting-1.md'
            - Governance Meeting 43: 'dac/meeting-notes/gov-meeting-43.md'
            - Governance Meeting 44: 'dac/meeting-notes/gov-meeting-44.md'
            - Governance Meeting 45: 'dac/meeting-notes/gov-meeting-45.md'
            - Governance Meeting 47: 'dac/meeting-notes/gov-meeting-47.md'
            - Governance Meeting 48: 'dac/meeting-notes/gov-meeting-48.md'
            - Governance Meeting 49: 'dac/meeting-notes/gov-meeting-49.md'
            - Governance Meeting 50: 'dac/meeting-notes/gov-meeting-50.md'

            - Community Meeting 53: 'dac/meeting-notes/community-meeting-53.md'
            - Community Meeting 54: 'dac/meeting-notes/community-meeting-54.md'
            - Community Meeting 55: 'dac/meeting-notes/community-meeting-55.md'
            - Community Meeting 56: 'dac/meeting-notes/community-meeting-56.md'
            - Community Meeting 57: 'dac/meeting-notes/community-meeting-57.md'
            - Community Meeting 58: 'dac/meeting-notes/community-meeting-58.md'
