site_name: 'Giveth Wiki'
site_url: https://wiki.giveth.io
site_author: 'The Unicorn DAC'
site_description: 'Learn about Giveth'
repo_url: https://github.com/Giveth/giveth-wiki/
edit_uri: edit/master/wiki/
docs_dir: wiki

theme_dir: material

google_analytics: ['UA-103956937-1', 'giveth.io']

extra:
    palette:
      primary: 'deep purple'
      accent: 'green'
    social:
    - type: 'slack'
      link: 'http://slack.giveth.io/'
    - type: 'twitter'
      link: 'https://twitter.com/givethio'
    - type: 'github'
      link: 'https://github.com/giveth'
    - type: 'facebook'
      link: 'https://facebook.com/givethio'
    - type: 'youtube'
      link: 'https://www.youtube.com/watch?v=VaIbmxk2eio&list=PL4Artm1rmCWGyz-BWv1-8Ip26XIauCLo9'

extra_css:
    - css/extra.css

pages:
    - Welcome: 'index.md'
    - Getting Started:
        - FAQ: 'documentation/faq.md'
        - Glossary: 'documentation/glossary.md'
    - Documentation:
        - MVP: 'documentation/mvp.md'
        - DApp Alpha: 'documentation/alpha.md'
        - White Paper: 'documentation/white-paper.md'
        - Design Assets: 'documentation/design-assets.md'
    - The Unicorn DAC:
      - About: 'dac/about.md'
      - Team Organisation: 'dac/team-organisation.md'
      - Finances: 'dac/finances.md'
      - Recruiting: 'dac/recruiting.md'
    - Protocol:
        - Governance Meetings:
          - Protocol for Governance Meetings: 'protocol/governance-meetings.md'
          - Governance Meeting 2017-09-19: 'protocol/gov-meeting-1.md'
          - Governance Meeting 2017-09-22: 'protocol/gov-meeting-2.md'
          - Governance Meeting 2017-09-29: 'protocol/gov-meeting-3.md'
          - Governance Meeting 2017-10-06: 'protocol/gov-meeting-4.md'
          - Governance Meeting 2017-10-13: 'protocol/gov-meeting-5.md'
          - Governance Meeting 2017-10-20: 'protocol/gov-meeting-6.md'
